### ISSUE TITLE
Howto: Compile Without VS

### ISSUE THREAD

**Issue by zhenchuan9r** [wow0000/GRE_Tunnel#1]
I think it would be better to adopt some open-source solutions for compiling, CMake eg.

**Comment by wow0000** [comment]
Hi !
Since this project was only made for a Windows usage, cmake would only have made things more complex for not much benefits.
I know that msvc isn't the best tool to work with but it does the job, I try to publish a pre-compiled release binary each time I push a new version to avoid dealing with issues on the user side

However, if you feel that this project truly require cmake, feel free to fork it :)
